### ISSUE TITLE
hashing is not done the same way in fe1 and fe2

### ISSUE THREAD

**Issue by Kar1213** [dedis/student_21_pop#360]
This problem was already mentioned but still not solved. In fe2 the hash values are always computed without including the length of the inputs as opposed to what is done in fe1. This makes the fe1 raise an error about the invalidity of the message id. From my understanding it is better to include them, so should we apply the change and use the same hashing as fe1 for the whole app?

**Comment by gnarula** [comment]
@Kar1213 Would help if you can point to a specific Hash calculation where the length is not considered. I reckon `MessageGeneral`'s generateId() method was one place but that has been fixed since f68a529e5

**Comment by Kar1213** [comment]
Sorry I didn't see that the length is included in the custom hash function we call. But we still get an error on fe1 about the message id and LAO id.

**Comment by pierluca** [comment]
I believe this issue was resolved. Closing as outdated.
